config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates_presence_of :title, :user_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]
  def index
    @articles = Article.all
  end

  def show
  end

  def test
  end


  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]
  
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:title, :description, :user_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2 class="white-color"><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field white-color">
    <%= form.label :title %>
    <%= form.text_field :title, class: "input-title", placeholder: "New Title" %> 
  </div> <br>

  <div class="field white-color"> 
    <%= form.label :body %>
    <%= form.text_area :body, class: "textarea-body", placeholder: "New Body" %>
  </div> <br>

  <div class="actions">
    <%= button_to "Create Article", "", class: "btn-create-article" %>
  </div>
<% end %>

app/views/articles/comments.html.erb
<h1>pojol ot suda<h1>

app/views/articles/edit.html.erb
<div class="card-edit-page motion-left">
    <h1>Editing Article</h1>

    <%= render 'form', article: @article %>

    <%= button_to 'Show', @article, class: "btn-show", method: :get %>
    <%= button_to 'Back', articles_path, class: "btn-back", method: :get %>
</div>

app/views/articles/index.html.erb
<div class="card-index-page motion-left">
  <p id="notice"><%= notice %></p>

  <h1 class="white-color">Articles</h1>

  <table class="table table-bordered border-secondary my-table">
    <thead>
      <tr>
        <th class="white-color">ID</th>
        <th class="white-color">Title</th>
        <th class="white-color">Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td class="white-color"><%= article.id %></td>
          <td class="white-color"><%= article.title %></td>
          <td class="white-color"><%= article.body %></td>
          <td><%= button_to 'Show', article, class: "btn-show", method: :get %></td>
          <td><%= button_to 'Edit', edit_article_path(article), class: "btn-edit", method: :get %></td>
          <td><%= button_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-destroy" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'New Article', new_article_path, class: "btn-new-article", method: :get %>
</div>

app/views/articles/new.html.erb
<div class="card-new-page motion-left">
    <h1 class="white-color">New Article</h1>

    <%= render 'form', article: @article %> 

    <%= button_to 'Back', articles_path, class: "btn-back", method: :get %>
</div>

app/views/articles/show.html.erb
<div class="card-show-page motion-left">
  <p id="notice"><%= notice %></p>

  <p>
    <strong class="white-color size-20px">ID:</strong>
    <div class="white-color size-20px">
      <%= @article.id %>
    </div>
  </p>

  <p>
    <strong class="white-color size-20px">Title:</strong>
    <div class="white-color size-20px">
      <%= @article.title %>
    </div>
  </p>

  <p>
    <strong class="white-color size-20px">Body:</strong>
    <div class="white-color size-20px">
      <%= @article.body %>
    </div>
  </p>

  <%= button_to 'Edit', edit_article_path(@article), class: "btn-edit", method: :get %> 
  <%= button_to 'Back', articles_path, class: "btn-back", method: :get %>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="field">
      <%= form.label :title %>
      <div>
        <%= form.text_field :title, class: "comments-input-title" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :description %>
      <div>
        <%= form.text_area :description, class: "comments-text_area-description" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :user_name %>
      <div>
        <%= form.text_field :user_name, class: "comments-input-user_name" %>
      </div>
    </div>

    <div>
      <%= button_to "Create Comment", "", class: "comments-btn-create-comment" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="center">
    <h1>Editing Comment</h1>

    <%= render 'form', comment: @comment %>

    <%= button_to 'Show', @comment, class: "comments-btn-show", method: :get %>
    <%= button_to 'Back', comments_path, class: "comments-btn-back", method: :get %>

</div>

app/views/comments/index.html.erb
<div>
  <p id="notice"><%= notice %></p>

  <h1>Comments</h1>

  <table class="table table-xxl align-middle table-bordered border-dark">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>User name</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.id %></td>
          <td><%= comment.title %></td>
          <td><%= comment.description %></td>
          <td><%= comment.user_name %></td>
          <td><%= button_to 'Show', comment, class: "comments-btn-show", method: :get %></td>
          <td><%= button_to 'Edit', edit_comment_path(comment), class: "comments-btn-edit", method: :get %></td>
          <td><%= button_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "comments-btn-destroy" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to 'New Comment', new_comment_path, class: "comments-btn-new-comment", method: :get %>
</div>

app/views/comments/new.html.erb
<div class="center">
    <h1>New Comment</h1>

    <%= render 'form', comment: @comment %>

    <%= button_to 'Back', comments_path, class: "comments-btn-back", method: :get %>

</div>

app/views/comments/show.html.erb
<div class="center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>ID:</strong>
    <%= @comment.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @comment.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @comment.description %>
  </p>

  <p>
    <strong>User name:</strong>
    <%= @comment.user_name %>
  </p>

  <p>
    <strong>Create Time:</strong>
    <%= @comment.created_at %>
  </p>

  <p>
    <strong>Uptade Time:</strong>
    <%= @comment.updated_at %>
  </p>

  <%= button_to 'Edit', edit_comment_path(@comment), class: "comments-btn-edit", method: :get %>
  <%= button_to 'Back', comments_path, class: "comments-btn-back", method: :get %>

</div>

app/views/layouts/_footer.html.erb
<footer class="card-footer motion-left">
  <p>
    <a href="#">up</a>
  </p>
  <p>my GitHub:  <a href="https://github.com/Mark228zzz", target="_blank"><i class='bx bxl-github'></i></p></a>
  <p>from 2021 to <%= Time.now.year %></p>
</footer>

app/views/layouts/_sidebar.html.erb
<div class="sidebar open">
  <div class="logo-details">
    <i class='bx bxl-bitcoin icon'></i>
      <div class="logo_name">Maznet</div>
      <i class='bx bx-menu' id="btn" ></i>
  </div>
  <ul class="nav-list">
    <li>
        <i class='bx bx-search' ></i>
       <input type="text" placeholder="Search...">
       <span class="tooltip">Search</span>
    </li>
    <li>
      <a href="/articles">
        <i class='bx bx-grid-alt'></i>
        <span class="links_name">All Articles</span>
      </a>
       <span class="tooltip">All Articles</span>
    </li>
   <li>
     <a href="/comments">
       <i class='bx bx-chat' ></i>
       <span class="links_name">Messages</span>
     </a>
     <span class="tooltip">Messages</span>
   </li>
   <li>
     <a href="#">
       <i class='bx bx-pie-chart-alt-2' ></i>
       <span class="links_name">Analytics</span>
     </a>
     <span class="tooltip">Analytics</span>
   </li>
   <li>
     <a href="#">
       <i class='bx bx-folder' ></i>
       <span class="links_name">File Manager</span>
     </a>
     <span class="tooltip">Files</span>
   </li>
   <li>
     <a href="#">
       <i class='bx bx-cart-alt' ></i>
       <span class="links_name">Order</span>
     </a>
     <span class="tooltip">Order</span>
   </li>
   <li>
     <a href="#">
       <i class='bx bx-heart' ></i>
       <span class="links_name">Saved</span>
     </a>
     <span class="tooltip">Saved</span>
   </li>
   <li>
     <a href="#">
       <i class='bx bx-cog' ></i>
       <span class="links_name">Settings</span>
     </a>
     <span class="tooltip">Settings</span>
   </li>
   
   <% if user_signed_in? %>
    <%= link_to current_user.email, edit_user_registration_path %> <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>


    <li class="profile">
       <div class="profile-details">
         <img src=<%= image_path("mark") %> alt="profileImg">
         <div class="name_job">
           <div class="name">Mark</div>
           <div class="job">Web designer</div>
         </div>
       </div>
       <i class='bx bx-log-out' id="log_out" ></i>
   </li>
   <% else %>
   <li>
     <a href="/users/sign_up">
       <i class='bx bx-log-in' ></i>
       <span class="links_name">Sign Up</span>
     </a>
     <span class="tooltip">Sign Up</span>
   </li>
    <li>
      <a href="/users/sign_in">
        <i class='bx bx-log-in' ></i>
        <span class="links_name">Sign In</span>
      </a>
      <span class="tooltip">Sign In</span>
    </li>
   <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maznet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

  </head>

  <body>
    <%= render 'layouts/sidebar' %>
    <div class="home-section">
      <div class="container test">
        <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
        <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>